upnp to find ip of a camera
viam-modules/viamrtsp pull request #58
Opened 2024-11-11 13:39 UTC by erh

2024-11-11 16:33 UTC, hexbabe commented on viamupnp/find.go
> +	cli := &http.Client{}
[nit] this will create a new http client per call. Should be okay though since this code path is run at most once per (re)configure?

2024-11-11 16:34 UTC, hexbabe commented on viamupnp/find.go
> +	cli := &http.Client{}
```
// near top of file
const httpTimeout = 10 * time.Second

// blah blah blah

client := &http.Client{
    Timeout: httpTimeout,
}
```

Might also be best practice to add a timeout

2024-11-11 16:38 UTC, hexbabe requested changes
Broad question: Is this what we're going with instead of a wrapper module? Or is that still a separate thing

2024-11-13 14:10 UTC, erh commented on rtsp.go
> +		host, err := viamupnp.FindHost(ctx, logger, conf.Query)
did something.

2024-11-13 14:25 UTC, erh commented
> Broad question: Is this what we're going with instead of a wrapper module? Or is that still a separate thing

getting rid of wrapper idea for now

2024-11-13 15:54 UTC, merged